# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imei_code',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Imei Celular'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('SUP', 'SUPERVISOR'), ('TEC', 'TECNICO')], default='TEC', max_length=3, verbose_name='Rol'),
        ),
    ]
