# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 21:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161012_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
    ]
