# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20160928_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=100, verbose_name=b'Nombres del Cliente')),
                ('address', models.CharField(max_length=100, verbose_name='Direcci\xf3n')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('mobile_phone', models.CharField(max_length=20, verbose_name='N\xfamero de Celular')),
                ('register_at', models.DateField(blank=True, null=True, verbose_name=b'Fecha de registro')),
                ('lat', models.IntegerField(blank=True, null=True, verbose_name=b'Latitud')),
                ('lng', models.IntegerField(blank=True, null=True, verbose_name=b'Longitud')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'permissions': (('report_job', 'Can Report Job'), ('show_job', 'Can Details Job'), ('index_job', 'Can List Job')),
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(verbose_name='Observaci\xf3n')),
                ('register_at', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha de Registro')),
                ('lat', models.IntegerField(blank=True, null=True, verbose_name=b'Latitud')),
                ('lng', models.IntegerField(blank=True, null=True, verbose_name=b'Longitud')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name=b'Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Trabajo',
                'verbose_name_plural': 'Historiales de trabajos',
                'permissions': (('show_jobhistory', 'Can Details Job History'), ('index_jobhistory', 'Can List Job Histories')),
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Tipo de Trabajo')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Tipo de Trabajo',
                'verbose_name_plural': 'Tipo de Trabajos',
                'permissions': (('show_jobtype', 'Can Details JobType'), ('index_jobtype', 'Can List JobType')),
            },
        ),
        migrations.CreateModel(
            name='ProfileJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'N', b'NUEVO'), (b'P', b'EN PROCESO'), (b'T', b'TERMINADO'), (b'D', b'DETENIDO')], default=b'N', max_length=100, verbose_name=b'Estado')),
                ('assign_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Asignaci\xf3n')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'verbose_name': 'Assignacion',
                'verbose_name_plural': 'Asignaciones',
                'permissions': (('show_pj', 'Can Details PJ'), ('index_pj', 'Can List PJ')),
            },
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='profilejob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.ProfileJob', verbose_name=b'Trabajo asignado'),
        ),
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobType', verbose_name=b'Tipo de Trabajo'),
        ),
    ]
