# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lat',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Latitud'),
        ),
        migrations.AlterField(
            model_name='job',
            name='lng',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Longitud'),
        ),
        migrations.AlterField(
            model_name='job',
            name='register_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name=b'Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='lat',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Latitud'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='lng',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Longitud'),
        ),
    ]
