# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20160929_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='register_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha de registro'),
        ),
    ]
