# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20161006_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[(b'NUEVO', b'NUEVO'), (b'EN_PROCESO', b'EN PROCESO'), (b'TERMINADO', b'TERMINADO'), (b'DETENIDO', b'DETENIDO')], default=b'NUEVO', max_length=10, verbose_name=b'Estado'),
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='state',
            field=models.CharField(choices=[(b'NUEVO', b'NUEVO'), (b'EN_PROCESO', b'EN PROCESO'), (b'TERMINADO', b'TERMINADO'), (b'DETENIDO', b'DETENIDO')], default=b'NUEVO', max_length=10, verbose_name=b'Estado'),
        ),
    ]
