# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20161006_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('report_job', 'Can Report Job'), ('show_job', 'Can Details Job'), ('index_job', 'Can List Job')), 'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job', verbose_name=b'Trabajo'),
        ),
        migrations.AlterField(
            model_name='profilejob',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name=b'Perfil'),
        ),
    ]
