# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:48
from __future__ import unicode_literals
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20161012_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilejob',
            options={'permissions': (('show_profilejob', 'Can Details Profije Job'), ('index_profilejob', 'Can List Profile Job')), 'verbose_name': 'Assignacion', 'verbose_name_plural': 'Asignaciones'},
        ),
    ]
