# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20161012_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'Tipo de Trabajo'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'Nombre de Zona'),
        ),
    ]
