# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20161028_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('report_job', 'Can Report Job'), ('show_job', 'Can Details Job'), ('index_job', 'Can List Job'), ('index_map_job', 'Can List Maps Job')), 'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
