# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_profilejob_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lat',
            field=models.CharField(max_length=50, verbose_name=b'Latitud'),
        ),
        migrations.AlterField(
            model_name='job',
            name='lng',
            field=models.CharField(max_length=50, verbose_name=b'Longitud'),
        ),
    ]
