# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_profile_register_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('LOW', 'BAJA'), ('MED', 'MEDIO'), ('HIG', 'ALTO')], max_length=3, verbose_name='Nivel de Alerta')),
                ('type', models.CharField(choices=[('MES', 'MENSAJE'), ('LOC', 'UBICACION')], max_length=3, verbose_name='Tipo de Alerta')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titulo')),
                ('content', models.CharField(blank=True, max_length=250, verbose_name='Contenido')),
                ('obj', models.CharField(max_length=25)),
                ('obj_id', models.CharField(max_length=5)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Emisor')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
