# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20161028_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': (('show_notification', 'Can Details Notificacion'), ('index_notification', 'Can List Notificacion')), 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
