# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20161028_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura'),
        ),
        migrations.AddField(
            model_name='notification',
            name='register_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de envio'),
        ),
    ]
